version: "3.8"

services:
  react_to_go_db:
    container_name: react_to_go_db
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: react_to_go_mysql
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  react_to_go_mysql:
    name: react_to_go_mysql